# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

project 'MapApp.xcodeproj'
target 'MapApp' do

source 'https://github.com/CocoaPods/Specs.git'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'ART',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
]

pod 'SalesforceAnalytics', :path => '../node_modules/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => '../node_modules/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => '../node_modules/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => '../node_modules/SalesforceMobileSDK-iOS'
pod 'SalesforceReact', :path => '../node_modules/SalesforceMobileSDK-iOS'
pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
